services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blue_pineapple
    ports:
      - "5434:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379"
