/**
 * @blue-pineapple/crm — public package surface.
 */

export type {
  CustomerStatus,
  CustomerType,
  ContactType,
  ContactPurpose,
  AddressType,
  ConsentChannel,
  ConsentType,
  RelationshipType,
  DocumentType,
  DocumentStatus,
  InteractionType,
  InteractionDirection,
  LoyaltyTier,
  TimelineEventType,
  CustomerData,
  CustomerProfile,
  CustomerInsights,
} from "./domain/crm.types";

export {
  CustomerPolicy,
  SegmentPolicy,
  LoyaltyPolicy,
  InteractionPolicy,
  DocumentPolicy,
  CRMBasePolicy,
} from "./policies";

export {
  customerService,
  customerContactService,
  customerAddressService,
  customerPreferenceService,
  customerSegmentService,
  customerTagService,
  customerTimelineService,
  customerInteractionService,
  customerConsentService,
  customerRelationshipService,
  customerDocumentService,
  loyaltyService,
  crmIntelligenceService,
  crmAuditService,
} from "./services";

export {
  crmController,
  customerContactController,
  customerAddressController,
  customerDetailController,
} from "./controllers";

export {
  CreateCustomerSchema,
  UpdateCustomerSchema,
  CreateCustomerContactSchema,
  CreateCustomerAddressSchema,
  CreateCustomerPreferenceSchema,
  CreateCustomerSegmentSchema,
  UpdateCustomerSegmentSchema,
  CreateCustomerTagSchema,
  CreateCustomerTimelineSchema,
  CreateCustomerInteractionSchema,
  CreateCustomerConsentSchema,
  CreateCustomerRelationshipSchema,
  CreateCustomerDocumentSchema,
  CreateLoyaltyTierSchema,
  CreateLoyaltyAccountSchema,
  CustomerSearchSchema,
  CustomerListSchema,
  CustomerStatusSchema,
  CustomerTypeSchema,
  ContactTypeSchema,
  ContactPurposeSchema,
  AddressTypeSchema,
  ConsentChannelSchema,
  ConsentTypeSchema,
  RelationshipTypeSchema,
  DocumentTypeSchema,
  DocumentStatusSchema,
  InteractionTypeSchema,
  LoyaltyTierSchema,
  TimelineEventTypeSchema,
} from "./validators/crm.schema";

export type {
  CreateCustomerSchemaType,
  CreateCustomerContactSchemaType,
  CreateCustomerAddressSchemaType,
  CreateCustomerPreferenceSchemaType,
  CreateCustomerSegmentSchemaType,
  UpdateCustomerSegmentSchemaType,
  CreateCustomerTagSchemaType,
  CreateCustomerTimelineSchemaType,
  CreateCustomerInteractionSchemaType,
  CreateCustomerConsentSchemaType,
  CreateCustomerRelationshipSchemaType,
  CreateCustomerDocumentSchemaType,
  CreateLoyaltyTierSchemaType,
  CreateLoyaltyAccountSchemaType,
} from "./validators/crm.schema";

export type {
  CustomerCreatedEvent,
  CustomerUpdatedEvent,
  CustomerStatusChangedEvent,
  CustomerContactAddedEvent,
  CustomerContactRemovedEvent,
  CustomerAddressAddedEvent,
  CustomerSegmentAssignedEvent,
  CustomerSegmentRemovedEvent,
  CustomerTagAddedEvent,
  CustomerTagRemovedEvent,
  CustomerPreferenceUpdatedEvent,
  CustomerTimelineEvent,
  CustomerInteractionCreatedEvent,
  CustomerConsentUpdatedEvent,
  CustomerRelationshipCreatedEvent,
  CustomerDocumentUploadedEvent,
  LoyaltyTierChangedEvent,
  LoyaltyPointsUpdatedEvent,
  CustomerMergedEvent,
  CustomerIntelligenceUpdatedEvent,
} from "./events/crm.events";
