export const DEPARTURE_STATUS = {
  SCHEDULED: "SCHEDULED" as const,
  BOARDING: "BOARDING" as const,
  DEPARTED: "DEPARTED" as const,
  COMPLETED: "COMPLETED" as const,
  CANCELLED: "CANCELLED" as const,
} as const;

export const DEPARTURE_ACTIVE_STATUSES: string[] = [
  DEPARTURE_STATUS.SCHEDULED,
  DEPARTURE_STATUS.BOARDING,
];

export const DEPARTURE_TERMINAL_STATUSES: string[] = [
  DEPARTURE_STATUS.COMPLETED,
  DEPARTURE_STATUS.CANCELLED,
];

export const DEPARTURE_NON_MODIFIABLE_STATUSES: string[] = [
  DEPARTURE_STATUS.DEPARTED,
  DEPARTURE_STATUS.COMPLETED,
  DEPARTURE_STATUS.CANCELLED,
];
