export const EXPERIENCES = [
  {
    name: "Fort Jesus Historical Boat Tour",
    slug: "fort-jesus",
    description:
      "A premium coastal cruise to Fort Jesus with iconic views and time to explore Old Town. Step aboard at Mombasa Beach and enjoy a journey past Nyali, Mombasa Marine Park, Likoni, and Shelly Beach before arriving at the magnificent Fort Jesus UNESCO World Heritage Site.",
    shortDescription:
      "A premium coastal cruise to Fort Jesus with iconic views and time to explore Old Town.",
    durationMinutes: 480,
    defaultPrice: 500,
    currency: "KES",
    category: "TRANSPORT",
    isFeatured: true,
    isActive: true,
    heroImageUrl: "/assets/experiences/fortjesus/fortstock.webp",
    galleryUrls: [
      "/assets/experiences/fortjesus/fort2.webp",
      "/assets/experiences/fortjesus/fort3.webp",
    ],
    maxGroupSize: 35,
    minGroupSize: 1,
    highlights: [
      "The Journey",
      "Coastal Views",
      "Fort Jesus",
      "Old Town Exploration",
    ],
    includes: [
      "Return Transport",
      "Professional Guide",
      "Fort Entry Tickets",
      "Bottled Water",
    ],
    requirements: [
      "Comfortable walking shoes",
      "Sun protection",
      "Camera",
    ],
  },
  {
    name: "Creek Safaris & Mangrove Exploration",
    slug: "creek-safaris-mangrove",
    description:
      "Glide through narrow channels lined with dense mangrove roots. The water is calm and mirror-like, perfect for spotting birdlife and small marine creatures. Switch on the glass-bottom panel and watch the underwater world beneath the boat — tropical fish, crabs, and coral formations in the shallow creek waters.",
    shortDescription:
      "Navigate the serene mangrove creeks and discover the underwater world through our glass-bottom boat.",
    durationMinutes: 180,
    defaultPrice: 4000,
    currency: "KES",
    category: "ADVENTURE",
    isFeatured: true,
    isActive: true,
    heroImageUrl: "/assets/experiences/creek/creek1.webp",
    galleryUrls: ["/assets/experiences/creek/creek2.webp"],
    maxGroupSize: 14,
    minGroupSize: 1,
    highlights: [
      "Mangrove creek navigation",
      "Glass-bottom viewing",
      "Birdlife spotting",
      "Eco-tourism education",
    ],
    includes: [
      "Boat charter",
      "Professional guide",
      "Bottled water",
      "Safety equipment",
    ],
    requirements: [
      "Comfortable clothing",
      "Sun hat",
      "Insect repellent",
    ],
  },
  {
    name: "Sunset Sailing",
    slug: "sunset-sailing",
    description:
      "Experience the magic of the Kenyan coast as the sun dips below the horizon. Our sunset sailing experience offers breathtaking views, cool ocean breezes, and the perfect ambiance for relaxation or celebration.",
    shortDescription:
      "Sail into the sunset along the Mombasa coastline with breathtaking ocean views.",
    durationMinutes: 150,
    defaultPrice: 3000,
    currency: "KES",
    category: "LEISURE",
    isFeatured: true,
    isActive: true,
    heroImageUrl: "/assets/experiences/sunset/sunset1.webp",
    galleryUrls: ["/assets/experiences/sunset/sunset2.webp"],
    maxGroupSize: 14,
    minGroupSize: 1,
    highlights: [
      "Golden hour sailing",
      "Panoramic coastline views",
      "Champagne on board",
      "Photo opportunities",
    ],
    includes: [
      "Boat charter",
      "Captain and crew",
      "Soft drinks and water",
      "Safety briefing",
    ],
    requirements: [
      "Light jacket recommended",
      "Sun protection",
      "Camera",
    ],
  },
  {
    name: "Snorkelling Reef Experience",
    slug: "snorkelling-reef",
    description:
      "Dive into the crystal-clear waters of Mombasa Marine Park and discover vibrant coral reefs and tropical fish. Our snorkelling experience is suitable for beginners and seasoned swimmers alike, with all equipment provided.",
    shortDescription:
      "Explore Mombasa Marine Park's vibrant coral reefs and tropical marine life.",
    durationMinutes: 120,
    defaultPrice: 2000,
    currency: "KES",
    category: "ADVENTURE",
    isFeatured: true,
    isActive: true,
    heroImageUrl: "/assets/experiences/snorkeling/snorkeling.webp",
    galleryUrls: [],
    maxGroupSize: 14,
    minGroupSize: 1,
    highlights: [
      "Coral reef exploration",
      "Tropical fish spotting",
      "Guided snorkelling",
      "Marine conservation talk",
    ],
    includes: [
      "Snorkelling equipment",
      "Life jacket",
      "Professional guide",
      "Bottled water",
    ],
    requirements: [
      "Swimming ability",
      "Sun protection",
      "Towel",
    ],
  },
  {
    name: "Birthdays & Anniversaries",
    slug: "birthdays-anniversaries",
    description:
      "Celebrate your special day on the water. Our birthday and anniversary packages are fully customisable — from decorations and cake to private dining and entertainment. Create unforgettable memories with Blue Pineapple.",
    shortDescription:
      "Fully customisable celebration packages on the water for birthdays and anniversaries.",
    durationMinutes: 120,
    defaultPrice: 2000,
    currency: "KES",
    category: "PRIVATE",
    isFeatured: false,
    isActive: true,
    heroImageUrl: "/assets/experiences/events/event1.webp",
    galleryUrls: ["/assets/experiences/events/event2.webp"],
    maxGroupSize: 35,
    minGroupSize: 1,
    highlights: [
      "Fully customisable",
      "Private event host",
      "Custom decorations",
      "Catering available",
    ],
    includes: [
      "Boat charter",
      "Event coordinator",
      "Sound system",
      "Bottled water",
    ],
    requirements: [
      "Advance booking required",
      "Custom requests 48h before",
    ],
  },
];
