export const REVIEWS = [
  {
    id: 'review-fort-jesus-1',
    experienceId: '1d171d13-a243-47ea-a0d6-a5959e06ab1e',
    bookingId: null,
    userId: null,
    guestName: 'Amina Otieno',
    guestEmail: 'amina.otieno@example.com',
    rating: 5,
    title: null,
    comment: 'Our Fort Jesus harbour trip was seamless — clear pricing, a calm crew, and views we still talk about. It felt premium without being complicated.',
    isApproved: true,
    isFeatured: true,
    helpfulCount: 12,
  },
  {
    id: 'review-fort-jesus-2',
    experienceId: '1d171d13-a243-47ea-a0d6-a5959e06ab1e',
    bookingId: null,
    userId: null,
    guestName: 'Daniel Kariuki',
    guestEmail: 'daniel.kariuki@example.com',
    rating: 5,
    title: null,
    comment: 'Hunky Dory was perfect with the kids. Glass-bottom viewing, life jackets ready, and captains who made everyone feel safe from start to finish.',
    isApproved: true,
    isFeatured: true,
    helpfulCount: 8,
  },
  {
    id: 'review-sunset-1',
    experienceId: 'b902de07-9702-4491-8fe3-87ab7a067b6b',
    bookingId: null,
    userId: null,
    guestName: 'Sophie Chen',
    guestEmail: 'sophie.chen@example.com',
    rating: 5,
    title: null,
    comment: 'The sunset sailing was beautifully paced. Clean boat, thoughtful crew, and that golden-hour light over Mombasa — exactly what we hoped for.',
    isApproved: true,
    isFeatured: true,
    helpfulCount: 15,
  },
  {
    id: 'review-sunset-2',
    experienceId: 'b902de07-9702-4491-8fe3-87ab7a067b6b',
    bookingId: null,
    userId: null,
    guestName: 'Brian Mwenda',
    guestEmail: 'brian.mwenda@example.com',
    rating: 4,
    title: null,
    comment: 'We chartered Setting Sons for a team day. Logistics were easy, the vessel felt polished, and the coastal route was a highlight for everyone.',
    isApproved: true,
    isFeatured: true,
    helpfulCount: 6,
  },
  {
    id: 'review-creek-1',
    experienceId: '676d5470-8674-4182-9ce5-ac607afc083b',
    bookingId: null,
    userId: null,
    guestName: 'James Mwangi',
    guestEmail: 'james.mwangi@example.com',
    rating: 5,
    title: null,
    comment: 'Gliding through the mangroves was magical. The glass-bottom panel was a hit with everyone on board. Highly recommend for families.',
    isApproved: true,
    isFeatured: false,
    helpfulCount: 4,
  },
  {
    id: 'review-snorkelling-1',
    experienceId: '8130b48a-365e-46cf-a9e7-e70f4c98b215',
    bookingId: null,
    userId: null,
    guestName: 'Caroline Wanjiku',
    guestEmail: 'caroline.wanjiku@example.com',
    rating: 4,
    title: null,
    comment: 'The coral reef was beautiful and the guide was very knowledgeable. Equipment was in good condition. Would definitely do again.',
    isApproved: true,
    isFeatured: false,
    helpfulCount: 3,
  },
];
